name: 78Generic Model Training
description: Generic training component for linear regression, logistic regression, and random forest models with automatic parameter validation

inputs:
  - name: processed_data
    type: String
    description: Processed training data pickle file
  - name: preprocessing_pipeline
    type: String
    description: Preprocessing pipeline pickle file
  - name: preprocessing_config
    type: String
    description: Preprocessing configuration JSON file
  - name: model_config
    type: String
    description: Model configuration JSON file

outputs:
  - name: output_trained_model
    type: String
    description: Trained model pickle file
  - name: output_training_history
    type: String
    description: Training history as JSON string

implementation:
  container:
    image: python:3.9
    command:
    - sh
    - -c
    args:
    - |-
      pip install pandas numpy scikit-learn joblib && \
      python -c "
      import json
      import pickle
      import pandas as pd
      from sklearn.linear_model import LogisticRegression, LinearRegression
      from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
      from sklearn.metrics import accuracy_score, mean_squared_error, classification_report
      import joblib

      # Load inputs
      with open('/tmp/inputs/model_config/data', 'r') as f:
          model_config = json.load(f)

      with open('/tmp/inputs/processed_data/data', 'rb') as f:
          processed_data = pickle.load(f)

      with open('/tmp/inputs/preprocessing_pipeline/data', 'rb') as f:
          preprocessing_pipeline = pickle.load(f)

      with open('/tmp/inputs/preprocessing_config/data', 'r') as f:
          preprocessing_config = json.load(f)

      # Extract data
      X_train = processed_data['X_train']
      X_test = processed_data['X_test']
      y_train = processed_data['y_train']
      y_test = processed_data['y_test']
      feature_names = processed_data['feature_names']

      model_type = model_config.get('model_type', 'logistic_regression')
      problem_type = model_config.get('problem_type', 'classification')

      # Model selection
      models = {
          'logistic_regression': LogisticRegression(random_state=42, max_iter=1000),
          'linear_regression': LinearRegression(),
          'random_forest_classifier': RandomForestClassifier(random_state=42, n_estimators=100),
          'random_forest_regressor': RandomForestRegressor(random_state=42, n_estimators=100)
      }

      # Select appropriate model
      if problem_type == 'classification':
          if model_type == 'logistic_regression':
              model = models['logistic_regression']
          elif model_type == 'random_forest':
              model = models['random_forest_classifier']
          else:
              model = models['logistic_regression']  # default
      else:  # regression
          if model_type == 'linear_regression':
              model = models['linear_regression']
          elif model_type == 'random_forest':
              model = models['random_forest_regressor']
          else:
              model = models['linear_regression']  # default

      # Train model
      print(f'Training {model_type} for {problem_type} problem...')
      model.fit(X_train, y_train)

      # Make predictions
      y_pred = model.predict(X_test)

      # Calculate metrics
      training_history = {}
      if problem_type == 'classification':
          accuracy = accuracy_score(y_test, y_pred)
          training_history = {
              'model_type': model_type,
              'problem_type': problem_type,
              'accuracy': float(accuracy),
              'feature_names': feature_names,
              'classes': list(model.classes_) if hasattr(model, 'classes_') else []
          }
          print(f'Test Accuracy: {accuracy:.4f}')
      else:
          mse = mean_squared_error(y_test, y_pred)
          training_history = {
              'model_type': model_type,
              'problem_type': problem_type,
              'mse': float(mse),
              'rmse': float(mse ** 0.5),
              'feature_names': feature_names
          }
          print(f'Test MSE: {mse:.4f}')
          print(f'Test RMSE: {mse ** 0.5:.4f}')

      # Save outputs
      import os
      os.makedirs('/tmp/outputs/output_trained_model', exist_ok=True)
      os.makedirs('/tmp/outputs/output_training_history', exist_ok=True)

      with open('/tmp/outputs/output_trained_model/data', 'wb') as f:
          pickle.dump(model, f)

      # Save training history as JSON string
      with open('/tmp/outputs/output_training_history/data', 'w') as f:
          json.dump(training_history, f)

      print('Training completed successfully!')
      "
